console.clear()

console.log('|============================================================|')
console.log('|                          Instabot                          |')
console.log('|============================================================|')
console.log('')

console.log('\x1b[32m| Login into instagram\x1b[0m')
console.log('| Check cookies saved in <Storage/cookies.json>')
console.log('| Cookies reset in this session ')
console.log('| Cookies not found ')
console.log('| Starting login with user <lxl3ehl53>')
console.log('| Close notification popup')
console.log('| Save cookies saved in <Storage/cookies.json> ')
console.log('')

console.log('\x1b[32m| Scrap profile names\x1b[0m')
console.log('| Open list of profiles that like the post ')
console.log('| Total: 08 -- 8 new saved profile names')
console.log('| Total: 16 -- 8 new saved profile names')
console.log('| Total: 24 -- 8 new saved profile names')
console.log('| Total: 32 -- 8 new saved profile names')
console.log('| Total: 40 -- 8 new saved profile names')
console.log('| Total: 48 -- 8 new saved profile names')
console.log('| Total: 56 -- 8 new saved profile names')
console.log('| Total: 64 -- 8 new saved profile names')
console.log('| Total: 72 -- 8 new saved profile names')
console.log('| Total: 80 -- 8 new saved profile names')
console.log('| Total: 88 -- 8 new saved profile names')
console.log('| Store profile names in <Storage/profiles.json>')
console.log('')

console.log('\x1b[32m| Like profile <marcus_91723>\x1b[0m')
console.log('| Number of profile followers: 436')
console.log('| Number of profile photo links collected: 7')
console.log('| Post liked: https://www.instagram.com/p/CX94-iKNLRa/')
console.log('| Post liked: https://www.instagram.com/p/CX94-wqesad/')
console.log('| Post liked: https://www.instagram.com/p/CX94-wqefva/')
console.log('| Post liked: https://www.instagram.com/p/CX94-nbgtrs/')
console.log('| Post liked: https://www.instagram.com/p/CX94-sacbtqa/')
console.log('| Post liked: https://www.instagram.com/p/CX94-adfdasf/')
console.log('| Post liked: https://www.instagram.com/p/CX94-grwwdvf/')
console.log('| Post liked: https://www.instagram.com/p/CX94-43hjfbgs/')
console.log('| Post liked: https://www.instagram.com/p/CX94-vbsr5egr/')
console.log('')

const err = new Error('Unable to connect to server')
console.group('\x1b[31m' + err.message + '\x1b[0m')
console.log(err)
console.groupEnd()
